### ISSUE TITLE
Naming for the first version of the Galaxy Pi

### ISSUE THREAD

**Issue by guylepage3** [galaxypi/operations#16]
Need to think quickly about the naming for the Galaxy Pi v1

**Comment by d-simon** [comment]
Is this a name for the code release?

**Comment by guylepage3** [comment]
@d-simon No. this is a name for the physical Galaxy Pi. Not to be confused with the v1 Micro-SD Card release.

**Comment by d-simon** [comment]
[dadi](https://dadi.cloud/) has chosen names like «Stargates», «Gateways», «Hosts» which I like a lot.

It would be great if it could be some galactic body. Like Planet, Star, Meteorite, Moon, Sun, Nebula, Star Cluster, Exoplanet etc.
Could also be named after a moon: e.g. [Deimos (moon)](https://en.wikipedia.org/wiki/Deimos_(moon)).
Or a astrological sign, but I'm personally not into those.

**Comment by guylepage3** [comment]
Closing issue.
