### ISSUE TITLE
Talk to Emin Gun Sirer about "snowflake to avalanche"

### ISSUE THREAD

**Issue by faddat** [galaxypi/operations#23]

**Comment by faddat** [comment]
https://www.youtube.com/watch?v=ahgTfFw6JVc

muratbuffalo.blogspot.com/2018/06/snowflake-to-avalanche-novel-metastable.html

https://www.coindesk.com/emin-gun-sirer-unveils-simple-yet-powerful-consensus-protocol/

https://davidgerard.co.uk/blockchain/2018/06/01/the-mathcoins-decentralised-cryptocurrency-without-the-blockchain/

https://flatoutcrypto.com/home/avalancheprotocol

So, basically this "Snowflake to Avalanche" is exactly what we need in that it solves "the hard problem"-- millions of actively participating nodes, that are nearly equal to each other.  

The interesting thing is that I've heard they're testing in the cloud.  A really amazing collaboration would be to help with their testnet on our fleet of Pi's using our build system.

**Comment by guylepage3** [comment]
@faddat 

- What is the ask?
- What is the goal?
- What do we want to ask about? 
- Is there any research I should do prior to pinging Emin?

**Comment by faddat** [comment]
See above comment.  we've been cross-posting.

**Comment by guylepage3** [comment]
Ok. I am going to ping Emin now.. He may take a few days to get back to us.

**Comment by guylepage3** [comment]
<img width="827" alt="screenshot 2018-07-09 08 10 15" src="https://user-images.githubusercontent.com/1711854/42449662-891fd858-834f-11e8-92e8-6cbd50a0e564.png">

**Comment by guylepage3** [comment]
Emin responded. @faddat see Slack. Closing issue. :)
